# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orders.proto',
  package='orders',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0corders.proto\x12\x06orders\"T\n\x11OrderItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"K\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\x0border_items\x18\x02 \x03(\x0b\x32\x19.orders.OrderItemResponse\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"M\n\x16\x43reateOrderItemRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"I\n\x12\x43reateOrderRequest\x12\x33\n\x0border_items\x18\x01 \x03(\x0b\x32\x1e.orders.CreateOrderItemRequest\"Y\n\x16UpdateOrderItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"U\n\x12UpdateOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x33\n\x0border_items\x18\x02 \x03(\x0b\x32\x1e.orders.UpdateOrderItemRequest\" \n\x12\x44\x65leteOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x14OrderDeletedResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x95\x02\n\x06orders\x12;\n\tget_order\x12\x17.orders.GetOrderRequest\x1a\x15.orders.OrderResponse\x12\x41\n\x0c\x63reate_order\x12\x1a.orders.CreateOrderRequest\x1a\x15.orders.OrderResponse\x12\x41\n\x0cupdate_order\x12\x1a.orders.UpdateOrderRequest\x1a\x15.orders.OrderResponse\x12H\n\x0c\x64\x65lete_order\x12\x1a.orders.DeleteOrderRequest\x1a\x1c.orders.OrderDeletedResponseb\x06proto3'
)




_ORDERITEMRESPONSE = _descriptor.Descriptor(
  name='OrderItemResponse',
  full_name='orders.OrderItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orders.OrderItemResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='orders.OrderItemResponse.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='orders.OrderItemResponse.price', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='orders.OrderItemResponse.quantity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=108,
)


_ORDERRESPONSE = _descriptor.Descriptor(
  name='OrderResponse',
  full_name='orders.OrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orders.OrderResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_items', full_name='orders.OrderResponse.order_items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=185,
)


_GETORDERREQUEST = _descriptor.Descriptor(
  name='GetOrderRequest',
  full_name='orders.GetOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orders.GetOrderRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=216,
)


_CREATEORDERITEMREQUEST = _descriptor.Descriptor(
  name='CreateOrderItemRequest',
  full_name='orders.CreateOrderItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='orders.CreateOrderItemRequest.product_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='orders.CreateOrderItemRequest.price', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='orders.CreateOrderItemRequest.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=295,
)


_CREATEORDERREQUEST = _descriptor.Descriptor(
  name='CreateOrderRequest',
  full_name='orders.CreateOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_items', full_name='orders.CreateOrderRequest.order_items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=370,
)


_UPDATEORDERITEMREQUEST = _descriptor.Descriptor(
  name='UpdateOrderItemRequest',
  full_name='orders.UpdateOrderItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orders.UpdateOrderItemRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='orders.UpdateOrderItemRequest.product_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='orders.UpdateOrderItemRequest.price', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='orders.UpdateOrderItemRequest.quantity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=461,
)


_UPDATEORDERREQUEST = _descriptor.Descriptor(
  name='UpdateOrderRequest',
  full_name='orders.UpdateOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orders.UpdateOrderRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_items', full_name='orders.UpdateOrderRequest.order_items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=548,
)


_DELETEORDERREQUEST = _descriptor.Descriptor(
  name='DeleteOrderRequest',
  full_name='orders.DeleteOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='orders.DeleteOrderRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=582,
)


_ORDERDELETEDRESPONSE = _descriptor.Descriptor(
  name='OrderDeletedResponse',
  full_name='orders.OrderDeletedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='orders.OrderDeletedResponse.deleted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='orders.OrderDeletedResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=640,
)

_ORDERRESPONSE.fields_by_name['order_items'].message_type = _ORDERITEMRESPONSE
_CREATEORDERREQUEST.fields_by_name['order_items'].message_type = _CREATEORDERITEMREQUEST
_UPDATEORDERREQUEST.fields_by_name['order_items'].message_type = _UPDATEORDERITEMREQUEST
DESCRIPTOR.message_types_by_name['OrderItemResponse'] = _ORDERITEMRESPONSE
DESCRIPTOR.message_types_by_name['OrderResponse'] = _ORDERRESPONSE
DESCRIPTOR.message_types_by_name['GetOrderRequest'] = _GETORDERREQUEST
DESCRIPTOR.message_types_by_name['CreateOrderItemRequest'] = _CREATEORDERITEMREQUEST
DESCRIPTOR.message_types_by_name['CreateOrderRequest'] = _CREATEORDERREQUEST
DESCRIPTOR.message_types_by_name['UpdateOrderItemRequest'] = _UPDATEORDERITEMREQUEST
DESCRIPTOR.message_types_by_name['UpdateOrderRequest'] = _UPDATEORDERREQUEST
DESCRIPTOR.message_types_by_name['DeleteOrderRequest'] = _DELETEORDERREQUEST
DESCRIPTOR.message_types_by_name['OrderDeletedResponse'] = _ORDERDELETEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderItemResponse = _reflection.GeneratedProtocolMessageType('OrderItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERITEMRESPONSE,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.OrderItemResponse)
  })
_sym_db.RegisterMessage(OrderItemResponse)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERRESPONSE,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.OrderResponse)
  })
_sym_db.RegisterMessage(OrderResponse)

GetOrderRequest = _reflection.GeneratedProtocolMessageType('GetOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETORDERREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.GetOrderRequest)
  })
_sym_db.RegisterMessage(GetOrderRequest)

CreateOrderItemRequest = _reflection.GeneratedProtocolMessageType('CreateOrderItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORDERITEMREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.CreateOrderItemRequest)
  })
_sym_db.RegisterMessage(CreateOrderItemRequest)

CreateOrderRequest = _reflection.GeneratedProtocolMessageType('CreateOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORDERREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.CreateOrderRequest)
  })
_sym_db.RegisterMessage(CreateOrderRequest)

UpdateOrderItemRequest = _reflection.GeneratedProtocolMessageType('UpdateOrderItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEORDERITEMREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.UpdateOrderItemRequest)
  })
_sym_db.RegisterMessage(UpdateOrderItemRequest)

UpdateOrderRequest = _reflection.GeneratedProtocolMessageType('UpdateOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEORDERREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.UpdateOrderRequest)
  })
_sym_db.RegisterMessage(UpdateOrderRequest)

DeleteOrderRequest = _reflection.GeneratedProtocolMessageType('DeleteOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEORDERREQUEST,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.DeleteOrderRequest)
  })
_sym_db.RegisterMessage(DeleteOrderRequest)

OrderDeletedResponse = _reflection.GeneratedProtocolMessageType('OrderDeletedResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERDELETEDRESPONSE,
  '__module__' : 'orders_pb2'
  # @@protoc_insertion_point(class_scope:orders.OrderDeletedResponse)
  })
_sym_db.RegisterMessage(OrderDeletedResponse)



_ORDERS = _descriptor.ServiceDescriptor(
  name='orders',
  full_name='orders.orders',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=643,
  serialized_end=920,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_order',
    full_name='orders.orders.get_order',
    index=0,
    containing_service=None,
    input_type=_GETORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='create_order',
    full_name='orders.orders.create_order',
    index=1,
    containing_service=None,
    input_type=_CREATEORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update_order',
    full_name='orders.orders.update_order',
    index=2,
    containing_service=None,
    input_type=_UPDATEORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete_order',
    full_name='orders.orders.delete_order',
    index=3,
    containing_service=None,
    input_type=_DELETEORDERREQUEST,
    output_type=_ORDERDELETEDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERS)

DESCRIPTOR.services_by_name['orders'] = _ORDERS

# @@protoc_insertion_point(module_scope)
