# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import orders_pb2 as orders__pb2


class ordersStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_order = channel.unary_unary(
                '/orders.orders/get_order',
                request_serializer=orders__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                )
        self.create_order = channel.unary_unary(
                '/orders.orders/create_order',
                request_serializer=orders__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                )
        self.update_order = channel.unary_unary(
                '/orders.orders/update_order',
                request_serializer=orders__pb2.UpdateOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                )
        self.delete_order = channel.unary_unary(
                '/orders.orders/delete_order',
                request_serializer=orders__pb2.DeleteOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderDeletedResponse.FromString,
                )


class ordersServicer(object):
    """Missing associated documentation comment in .proto file"""

    def get_order(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_order(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_order(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_order(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ordersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_order': grpc.unary_unary_rpc_method_handler(
                    servicer.get_order,
                    request_deserializer=orders__pb2.GetOrderRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
            'create_order': grpc.unary_unary_rpc_method_handler(
                    servicer.create_order,
                    request_deserializer=orders__pb2.CreateOrderRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
            'update_order': grpc.unary_unary_rpc_method_handler(
                    servicer.update_order,
                    request_deserializer=orders__pb2.UpdateOrderRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
            'delete_order': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_order,
                    request_deserializer=orders__pb2.DeleteOrderRequest.FromString,
                    response_serializer=orders__pb2.OrderDeletedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.orders', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class orders(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def get_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.orders/get_order',
            orders__pb2.GetOrderRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def create_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.orders/create_order',
            orders__pb2.CreateOrderRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.orders/update_order',
            orders__pb2.UpdateOrderRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orders.orders/delete_order',
            orders__pb2.DeleteOrderRequest.SerializeToString,
            orders__pb2.OrderDeletedResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
