version: '3.5'

services:

  db_center_cassandra: # Use Cassandra for document database
    image: bitnami/cassandra:latest
    ports: 
      - 49042:9042
    volumes:
      - ./docker/db_center_cassandra/volumes/dbdata:/bitnami/cassandra/data
      
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "55439:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  products:
    build: ./products
    volumes: 
      - ./products:/service/products/
    env_file: ./products/.env

  orders:
    build: ./orders
    volumes: 
      - ./orders:/service/orders/

  gateway: 
    build: ./gateway
    ports: 
      - 4000:4000
    # environment: 
    #   - ORDERS_SERVICE=orders
    #   - PRODUCTS_SERVICE=products


volumes:
  postgres:
  pgadmin: