# Read .env file
# ifndef DB_HOST
# 	# Determine if .env file exist
# ifneq ("$(wildcard .env)","")
# 	include .env
# endif
# endif

# export DB_DRIVER=cassandra
# export DB_HOST=db_center_cassandra
# export DB_PORT=49042
# export DB_USER=cassandra
# export DB_PASSWORD=cassandra

test:
	pytest